[default_kernels]
git-tree-sha1 = "fea67c2b672720909ba37113a72233188285ee4b"
lazy = true

    [[default_kernels.download]]
    sha256 = ""
    url = "https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/de430.bsp"

[mars_kernels]
git-tree-sha1 = "18cab005687dfb01d3ae8d8268c9e514e5484966"
lazy = true

    [[mars_kernels.download]]
    sha256 = ""
    url = "https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/satellites/mar097.bsp"

[meta_kernels]
git-tree-sha1 = "e8a47780a03e065c206d7760bfda6597edb8bf85"
lazy = true

    [[meta_kernels.download]]
    sha256 = ""
    url = "https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/pck00010.tpc"
    [[meta_kernels.download]]
    sha256 = ""
    url = "https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/gm_de431.tpc"
    [[meta_kernels.download]]
    sha256 = ""
    url = "https://naif.jpl.nasa.gov/pub/naif/generic_kernels/lsk/latest_leapseconds.tls"

[neptune_kernels]
git-tree-sha1 = "82bc076ca3cef671a0732311c9077bf1eb3c200e"
lazy = true

    [[neptune_kernels.download]]
    sha256 = ""
    url = "https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/satellites/nep095.bsp"

[pluto_kernels]
git-tree-sha1 = "796a33ff7a282214952fe2cf79c40847b9279f19"
lazy = true

    [[pluto_kernels.download]]
    sha256 = ""
    url = "https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/satellites/plu055.bsp"

[saturn_kernels]
git-tree-sha1 = "467a386da55c1f1206a7449136947bbcb66e6f26"
lazy = true

    [[saturn_kernels.download]]
    sha256 = ""
    url = "https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/satellites/sat427.bsp"

[uranus_kernels]
git-tree-sha1 = "cc6c7abc208548e4c85f6f4019501ad105ed4f37"
lazy = true

    [[uranus_kernels.download]]
    sha256 = ""
    url = "https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/satellites/ura111.bsp"
